apiVersion: v1
kind: Service
metadata:
  name: cactus-api-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: cactus-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000